# pandas

- Pandas is one of the most commonly used Python packages/libraries/modules for data science.<br><br>
- Pandas is Python's answer for making two dimensional tables (ala Excel and SQL).<br><br>
- Pandas calls a table a "DataFrame".<br><br>
- Pandas DataFrames are used by Python's other packages for statistical analysis, data manipulation, and data visualization.<br><br>
- Pandas DataFrames can be exported as .csv and other files.<br><br>

The pandas syntax isn't very instinctual. Some of the syntax will differ from basic Python. I still have to look a lot of things up in pandas, if it's something I don't do very often. However, it is the tool for working with spreadsheets in Python, so you'll need to learn it at some point.<br><br>
Pandas is written as more of a *functional* language than basic Python. This means that instead of manipulating objects, we'll be applying more functions across our data.

#### <br>Why do we work with Jupyter Notebooks for data science?

Jupyter Notebooks allow us to view nicely formatted output (such as pandas DataFrames and data visualizations) directly below the code used to create the object. They also allow you to scroll through large DataFrames or images.

#### <br>NumPy arrays
This week is going to focus on the Python package Pandas. However, Pandas (and many other Python packages) are built on NumPy arrays. NumPy is another Python module, and NumPy arrays are multi-dimensional datasets made up entirely of numerical data. They allow for much faster calculations than other basic Python objects. If you work with large numerical datasets, you will also want to look into the NumPy package. NumPy arrays do not have the features that many of us want to work with, such as column headers and the ability to work with non-numerical data; that's why pandas is so popular.

## <br><br><br>Importing pandas

Because pandas is one of the most commonly used Python packages, it often gets imported as a shortened version of it's actual name. This makes it quicker to type.

In [1]:
import pandas as pd

Pandas comes with the Anaconda distribution of Python and is available on Google Colab.

## <br><br><br>PART ONE: LOADING AND VIEWING DATAFRAMES

### <br>Opening files from your computer

#### If you are using Google Colab, you must run the next line of code. *If you are NOT using Google Colab, do NOT run the next line.*
Google Colab requires you to load data files into your workspace by hand (or by using this trick to pull them in from github).

In [ ]:
!wget https://github.com/Milan-Chicago/Introduction-to-Python/blob/main/Day%205/wnba-team-elo-ratings.csv
!wget https://github.com/Milan-Chicago/Introduction-to-Python/blob/main/Day%205/pigeonRacing.txt
!wget https://github.com/Milan-Chicago/Introduction-to-Python/blob/main/Day%205/zoo.xlsx

### <br><br><br>Loading a csv file

We will use the function `pd.read_csv()`. As a reminder, when we use a function from an imported module, we first give the module's name, followed by a dot, followed by the function name.
<br><br>This will automatically create a **DataFrame** object, which we are saving as `df`. `df` is a common variable name for a DataFrame. You can open the file, define it as a Pandas DataFrame, assign it to a variable, and close the file in one line. (Already we're seeing the differences from basic Python).

In [2]:
df = pd.read_csv("wnba-team-elo-ratings.csv")

<br><br>Our sample dataset was taken from FiveThirtyEight. It contains game data for WNBA games since 1997.

### <br><br><br>Viewing the DataFrame

In [3]:
df

season        date team1 team2                name1  \
0        2019  10/10/2019   WAS   CON   Washington Mystics   
1        2019  10/10/2019   CON   WAS      Connecticut Sun   
2        2019   10/8/2019   WAS   CON   Washington Mystics   
3        2019   10/8/2019   CON   WAS      Connecticut Sun   
4        2019   10/6/2019   WAS   CON   Washington Mystics   
...       ...         ...   ...   ...                  ...   
10483    1997   6/21/1997   SAC   LVA  Sacramento Monarchs   
10484    1997   6/21/1997   NYL   LAS     New York Liberty   
10485    1997   6/21/1997   LAS   NYL   Los Angeles Sparks   
10486    1997   6/21/1997   LVA   SAC          Utah Starzz   
10487    1997   6/21/1997   CLE   HOU    Cleveland Rockers   

                     name2  neutral  playoff  score1  score2  elo1_pre  \
0          Connecticut Sun        0        1      89      78      1684   
1       Washington Mystics        0        1      78      89      1634   
2          Connecticut Sun        0        1      86      90      1693   
3       Washington Mystics        0        1      90      86      1626   
4          Connecticut Sun        0        1      94      81      1671   
...                    ...      ...      ...     ...     ...       ...   
10483          Utah Starzz        0        0      73      61      1500   
10484   Los Angeles Sparks        0        0      67      57      1500   
10485     New York Liberty        0        0      57      67      1500   
10486  Sacramento Monarchs        0        0      61      73      1500   
10487       Houston Comets        0        0      56      76      1500   

       elo2_pre  elo1_post  elo2_post  prob1  is_home1  
0          1634       1692       1627  0.718         1  
1          1684       1627       1692  0.282         0  
2          1626       1684       1634  0.476         0  
3          1693       1634       1684  0.524         1  
4          1648       1693       1626  0.399         0  
...         ...        ...        ...    ...       ...  
10483      1500       1521       1479  0.387         0  
10484      1500       1519       1481  0.387         0  
10485      1500       1481       1519  0.613         1  
10486      1500       1479       1521  0.613         1  
10487      1500       1470       1530  0.613         1  

[10488 rows x 16 columns]

<br>Take a minute to look at the data. The DataFrame will have a slightly different look on Colab and Jupyter, and on different versions of Jupyter.
<br><br>The number at the beginning of each row is called an **index**. The index was automatically assigned by pandas when the dataset was loaded. It was not in the original csv file. It is merely a series of consecutive numbers going down the rows. The rows were loaded in whatever order they were in the csv file.

If you are working in Google Colab, there is a new feature that lets you magically convert your DataFrame into an interactive table. We're NOT going to use that feature, though you can feel free to explore it on your own time. 

<br><br>There are ways to view pieces of the DataFrame. Try these to see what they do:

In [4]:
df.head()

season        date team1 team2               name1               name2  \
0    2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun   
1    2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics   
2    2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun   
3    2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics   
4    2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun   

   neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
0        0        1      89      78      1684      1634       1692       1627   
1        0        1      78      89      1634      1684       1627       1692   
2        0        1      86      90      1693      1626       1684       1634   
3        0        1      90      86      1626      1693       1634       1684   
4        0        1      94      81      1671      1648       1693       1626   

   prob1  is_home1  
0  0.718         1  
1  0.282         0  
2  0.476         0  
3  0.524         1  
4  0.399         0

In [5]:
df.head(10)

season        date team1 team2               name1               name2  \
0    2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun   
1    2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics   
2    2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun   
3    2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics   
4    2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun   
5    2019   10/6/2019   CON   WAS     Connecticut Sun  Washington Mystics   
6    2019   10/1/2019   WAS   CON  Washington Mystics     Connecticut Sun   
7    2019   10/1/2019   CON   WAS     Connecticut Sun  Washington Mystics   
8    2019   9/29/2019   WAS   CON  Washington Mystics     Connecticut Sun   
9    2019   9/29/2019   CON   WAS     Connecticut Sun  Washington Mystics   

   neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
0        0        1      89      78      1684      1634       1692       1627   
1        0        1      78      89      1634      1684       1627       1692   
2        0        1      86      90      1693      1626       1684       1634   
3        0        1      90      86      1626      1693       1634       1684   
4        0        1      94      81      1671      1648       1693       1626   
5        0        1      81      94      1648      1671       1626       1693   
6        0        1      87      99      1700      1618       1671       1648   
7        0        1      99      87      1618      1700       1648       1671   
8        0        1      95      86      1694      1624       1700       1618   
9        0        1      86      95      1624      1694       1618       1700   

   prob1  is_home1  
0  0.718         1  
1  0.282         0  
2  0.476         0  
3  0.524         1  
4  0.399         0  
5  0.601         1  
6  0.763         1  
7  0.237         0  
8  0.747         1  
9  0.253         0

In [6]:
df.tail()

season       date team1 team2                name1  \
10483    1997  6/21/1997   SAC   LVA  Sacramento Monarchs   
10484    1997  6/21/1997   NYL   LAS     New York Liberty   
10485    1997  6/21/1997   LAS   NYL   Los Angeles Sparks   
10486    1997  6/21/1997   LVA   SAC          Utah Starzz   
10487    1997  6/21/1997   CLE   HOU    Cleveland Rockers   

                     name2  neutral  playoff  score1  score2  elo1_pre  \
10483          Utah Starzz        0        0      73      61      1500   
10484   Los Angeles Sparks        0        0      67      57      1500   
10485     New York Liberty        0        0      57      67      1500   
10486  Sacramento Monarchs        0        0      61      73      1500   
10487       Houston Comets        0        0      56      76      1500   

       elo2_pre  elo1_post  elo2_post  prob1  is_home1  
10483      1500       1521       1479  0.387         0  
10484      1500       1519       1481  0.387         0  
10485      1500       1481       1519  0.613         1  
10486      1500       1479       1521  0.613         1  
10487      1500       1470       1530  0.613         1

In [7]:
df.tail(2)

season       date team1 team2              name1                name2  \
10486    1997  6/21/1997   LVA   SAC        Utah Starzz  Sacramento Monarchs   
10487    1997  6/21/1997   CLE   HOU  Cleveland Rockers       Houston Comets   

       neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
10486        0        0      61      73      1500      1500       1479   
10487        0        0      56      76      1500      1500       1470   

       elo2_post  prob1  is_home1  
10486       1521  0.613         1  
10487       1530  0.613         1

In [8]:
df.sample()

season       date team1 team2                name1           name2  \
10375    1997  7/25/1997   SAC   HOU  Sacramento Monarchs  Houston Comets   

       neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
10375        0        0      76      86      1427      1585       1417   

       elo2_post  prob1  is_home1  
10375       1595   0.39         1

In [9]:
df.sample(6)

season       date team1 team2             name1                name2  \
8451     2001  8/27/2001   NYL   CHA  New York Liberty      Charlotte Sting   
10470    1997  6/26/1997   LVA   CLE       Utah Starzz    Cleveland Rockers   
8025     2002   8/1/2002   LVA   SAC       Utah Starzz  Sacramento Monarchs   
7787     2003  6/17/2003   IND   CHA     Indiana Fever      Charlotte Sting   
8990     2001  5/28/2001   HOU   LAS    Houston Comets   Los Angeles Sparks   
2306     2014   8/5/2014   PHO   ATL   Phoenix Mercury        Atlanta Dream   

       neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
8451         0        1      44      48      1534      1549       1523   
10470        0        0      63      74      1491      1470       1479   
8025         0        0      71      80      1571      1458       1556   
7787         0        0      71      60      1502      1511       1514   
8990         0        0      63      66      1621      1581       1610   
2306         0        0      75      67      1698      1543       1703   

       elo2_post  prob1  is_home1  
8451        1561  0.615         1  
10470       1482  0.416         0  
8025        1473  0.548         0  
7787        1499  0.601         1  
8990        1592  0.667         1  
2306        1538  0.795         1

### <br><br><br>Loading other types of files

We can open a tab-separated file using the same function we used to open a csv. We just have to pass a second argument, a **keyword argument**, to tell it that the delimiter is a tab instead of the default (comma). This dataset contains rankings of profressional racing pigeons.

In [10]:
pigeon_df = pd.read_csv("pigeonRacing.txt", delimiter="\t")

In [11]:
pigeon_df.head()

Position Avg Unirate              Name     Racing Pigeon Color Sex  \
0         1       0.26%      Dean Schultz    751 AU 18 PURP    BB   F   
1         2       1.08%       Dick Fassio    9027 AU 19 SLI  BBAR   F   
2         3       1.42%       Gary Mosher    32826 AU 17 AA   BKC   F   
3         4       2.21%  Todd Bartholomew  35624 AU 17 JEDD    BC   F   
4         5       2.61%   Dustin Maxfield    3322 AU 17 OGN    BB   M   

  Qualifying Race Miles  Average Birdage  
0              469, 469            612.0  
1              579, 500            139.0  
2              494, 539            103.0  
3              547, 468            226.0  
4              462, 462            171.0

<br><br>We will use a different function to open an Excel file. This file has information about animals and has two sheets within the excel file. We will first load sheet 1 and then sheet 2. We have to pass the `read_excel()` function one extra argument to specify the sheet:

In [12]:
zoo_df = pd.read_excel("zoo.xlsx", sheet_name=0)

In [13]:
zoo_df.head()

animal  hair  feathers  eggs  milk  airbourne  aquatic  predator  \
0  aardvark     1         0     0     1          0        0         1   
1  antelope     1         0     0     1          0        0         0   
2      bass     0         0     1     0          0        1         1   
3      bear     1         0     0     1          0        0         1   
4      boar     1         0     0     1          0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [14]:
zoo_class_df = pd.read_excel("zoo.xlsx", sheet_name=1)

In [15]:
zoo_class_df.head()

Unnamed: 0      class
0           1     mammal
1           2       bird
2           3    reptile
3           4       fish
4           5  amphibian

### <br><br>Exercise 1

Try to load two or three files from your own computer into pandas. Try with at least two different file types (csv, tab-delimited, excel). You can copy and paste the files into today's workshop folder, or you can open them by using the full path to the file (for example, "\~/Documents/myfolder/myfile.xlsx" or "\~\Documents\myfolder\myfile.csv").

<br>**If you are using Google Colab**, you will need to upload the files to Colab yourself. You can do this by clicking on the folder on the left menu. You should see a file tree come up that includes sample_data. Right click anywhere in this space and choose upload to upload your own files.

### <br><br><br>Getting basic info about the DataFrame

You can use the `len()` function to find out how many rows are in a DataFrame object:

In [16]:
len(df)

10488

<br>The `describe()` method will give you some very basic stats about each column in your DataFrame:

In [17]:
df.describe()

season  neutral       playoff        score1        score2  \
count  10488.000000  10488.0  10488.000000  10488.000000  10488.000000   
mean    2008.094775      0.0      0.073227     74.171815     74.171815   
std        6.361955      0.0      0.260520     12.409629     12.409629   
min     1997.000000      0.0      0.000000      0.000000      0.000000   
25%     2003.000000      0.0      0.000000     66.000000     66.000000   
50%     2008.000000      0.0      0.000000     74.000000     74.000000   
75%     2014.000000      0.0      0.000000     82.000000     82.000000   
max     2019.000000      0.0      1.000000    127.000000    127.000000   

           elo1_pre      elo2_pre     elo1_post     elo2_post         prob1  \
count  10488.000000  10488.000000  10488.000000  10488.000000  10488.000000   
mean    1493.718440   1493.718440   1493.717868   1493.717868      0.500000   
std       87.037547     87.037547     88.109043     88.109043      0.184767   
min     1183.000000   1183.000000   1168.000000   1168.000000      0.049000   
25%     1442.000000   1442.000000   1441.000000   1441.000000      0.358000   
50%     1498.000000   1498.000000   1497.000000   1497.000000      0.500000   
75%     1549.000000   1549.000000   1549.000000   1549.000000      0.642000   
max     1741.000000   1741.000000   1743.000000   1743.000000      0.951000   

           is_home1  
count  10488.000000  
mean       0.500000  
std        0.500024  
min        0.000000  
25%        0.000000  
50%        0.500000  
75%        1.000000  
max        1.000000

<br>The `shape` attribute will return the number of rows and columns as a tuple. An attribute gives us some stored data about an object - it is not a method function, so it does not get parentheses.

In [18]:
df.shape

(10488, 16)

You can even save the shape tuple as an object, in case you need to include it in any code:

In [19]:
df_shape = df.shape

In [20]:
print("Our DataFrame has " + str(df_shape[0]) + " rows and " + str(df_shape[1]) + " columns.")

Our DataFrame has 10488 rows and 16 columns.


<br>The `size` attribute will tell you the total number of elements in the DataFrame (size = rows x columns):

In [21]:
df.size

167808

<br>To return a list of the column names, you can start with the `columns` attribute:

In [22]:
df.columns

Index(['season', 'date', 'team1', 'team2', 'name1', 'name2', 'neutral',
       'playoff', 'score1', 'score2', 'elo1_pre', 'elo2_pre', 'elo1_post',
       'elo2_post', 'prob1', 'is_home1'],
      dtype='object')

Hmm. That looks strange because it is a pandas object. You can make it into a list so that it is easier to work with:

In [23]:
column_names = list(df.columns)
print(column_names)

['season', 'date', 'team1', 'team2', 'name1', 'name2', 'neutral', 'playoff', 'score1', 'score2', 'elo1_pre', 'elo2_pre', 'elo1_post', 'elo2_post', 'prob1', 'is_home1']


<br>To find out the data types of the data found in each column, use the `dtypes` attribute:

In [24]:
df.dtypes

season         int64
date          object
team1         object
team2         object
name1         object
name2         object
neutral        int64
playoff        int64
score1         int64
score2         int64
elo1_pre       int64
elo2_pre       int64
elo1_post      int64
elo2_post      int64
prob1        float64
is_home1       int64
dtype: object

<br>To **transpose** a DataFrame (swap the rows and columns), you also use an attribute. Let's transpose `zoo_df`:

In [25]:
zoo_df.T

0         1     2     3     4        5     6     7        8    \
animal     aardvark  antelope  bass  bear  boar  buffalo  calf  carp  catfish   
hair              1         1     0     1     1        1     1     0        0   
feathers          0         0     0     0     0        0     0     0        0   
eggs              0         0     1     0     0        0     0     1        1   
milk              1         1     0     1     1        1     1     0        0   
airbourne         0         0     0     0     0        0     0     0        0   
aquatic           0         0     1     0     0        0     0     1        1   
predator          1         0     1     1     1        0     0     0        1   
toothed           1         1     1     1     1        1     1     1        1   
backbone          1         1     1     1     1        1     1     1        1   
breathes          1         1     0     1     1        1     1     0        0   
venomous          0         0     0     0     0        0     0     0        0   
fins              0         0     1     0     0        0     0     1        1   
legs              4         4     0     4     4        4     4     0        0   
tail              0         1     1     0     1        1     1     1        1   
domestic          0         0     0     0     0        0     1     1        0   
catsize           1         1     0     1     1        1     1     0        0   
type              1         1     4     1     1        1     1     4        4   

            9    ...      91    92       93    94       95       96    97   \
animal     cavy  ...  tuatara  tuna  vampire  vole  vulture  wallaby  wasp   
hair          1  ...        0     0        1     1        0        1     1   
feathers      0  ...        0     0        0     0        1        0     0   
eggs          0  ...        1     1        0     0        1        0     1   
milk          1  ...        0     0        1     1        0        1     0   
airbourne     0  ...        0     0        1     0        1        0     1   
aquatic       0  ...        0     1        0     0        0        0     0   
predator      0  ...        1     1        0     0        1        0     0   
toothed       1  ...        1     1        1     1        0        1     0   
backbone      1  ...        1     1        1     1        1        1     0   
breathes      1  ...        1     0        1     1        1        1     1   
venomous      0  ...        0     0        0     0        0        0     1   
fins          0  ...        0     1        0     0        0        0     0   
legs          4  ...        4     0        2     4        2        2     6   
tail          0  ...        1     1        1     1        1        1     0   
domestic      1  ...        0     0        0     0        0        0     0   
catsize       0  ...        0     1        0     0        1        1     0   
type          1  ...        3     4        1     1        2        1     6   

            98    99    100  
animal     wolf  worm  wren  
hair          1     0     0  
feathers      0     0     1  
eggs          0     1     1  
milk          1     0     0  
airbourne     0     0     1  
aquatic       0     0     0  
predator      1     0     0  
toothed       1     0     0  
backbone      1     0     1  
breathes      1     1     1  
venomous      0     0     0  
fins          0     0     0  
legs          4     0     2  
tail          1     0     1  
domestic      0     0     0  
catsize       1     0     0  
type          1     7     2  

[18 rows x 101 columns]

<br>Let's see if that changed our DataFrame object:

In [26]:
zoo_df

animal  hair  feathers  eggs  milk  airbourne  aquatic  predator  \
0    aardvark     1         0     0     1          0        0         1   
1    antelope     1         0     0     1          0        0         0   
2        bass     0         0     1     0          0        1         1   
3        bear     1         0     0     1          0        0         1   
4        boar     1         0     0     1          0        0         1   
..        ...   ...       ...   ...   ...        ...      ...       ...   
96    wallaby     1         0     0     1          0        0         0   
97       wasp     1         0     1     0          1        0         0   
98       wolf     1         0     0     1          0        0         1   
99       worm     0         0     1     0          0        0         0   
100      wren     0         1     1     0          1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  type  
0          1     1  
1          1     1  
2          0     4  
3          1     1  
4          1     1  
..       ...   ...  
96         1     1  
97         0     6  
98         1     1  
99         0     7  
100        0     2  

[101 rows x 18 columns]

<br><br>It didn't change! DataFrames are **immutable objects** like strings and numpy arrays. To save the transposed DataFrame, we would have to reassign it to a variable:

In [27]:
zoo_df_t = zoo_df.T
zoo_df_t

0         1     2     3     4        5     6     7        8    \
animal     aardvark  antelope  bass  bear  boar  buffalo  calf  carp  catfish   
hair              1         1     0     1     1        1     1     0        0   
feathers          0         0     0     0     0        0     0     0        0   
eggs              0         0     1     0     0        0     0     1        1   
milk              1         1     0     1     1        1     1     0        0   
airbourne         0         0     0     0     0        0     0     0        0   
aquatic           0         0     1     0     0        0     0     1        1   
predator          1         0     1     1     1        0     0     0        1   
toothed           1         1     1     1     1        1     1     1        1   
backbone          1         1     1     1     1        1     1     1        1   
breathes          1         1     0     1     1        1     1     0        0   
venomous          0         0     0     0     0        0     0     0        0   
fins              0         0     1     0     0        0     0     1        1   
legs              4         4     0     4     4        4     4     0        0   
tail              0         1     1     0     1        1     1     1        1   
domestic          0         0     0     0     0        0     1     1        0   
catsize           1         1     0     1     1        1     1     0        0   
type              1         1     4     1     1        1     1     4        4   

            9    ...      91    92       93    94       95       96    97   \
animal     cavy  ...  tuatara  tuna  vampire  vole  vulture  wallaby  wasp   
hair          1  ...        0     0        1     1        0        1     1   
feathers      0  ...        0     0        0     0        1        0     0   
eggs          0  ...        1     1        0     0        1        0     1   
milk          1  ...        0     0        1     1        0        1     0   
airbourne     0  ...        0     0        1     0        1        0     1   
aquatic       0  ...        0     1        0     0        0        0     0   
predator      0  ...        1     1        0     0        1        0     0   
toothed       1  ...        1     1        1     1        0        1     0   
backbone      1  ...        1     1        1     1        1        1     0   
breathes      1  ...        1     0        1     1        1        1     1   
venomous      0  ...        0     0        0     0        0        0     1   
fins          0  ...        0     1        0     0        0        0     0   
legs          4  ...        4     0        2     4        2        2     6   
tail          0  ...        1     1        1     1        1        1     0   
domestic      1  ...        0     0        0     0        0        0     0   
catsize       0  ...        0     1        0     0        1        1     0   
type          1  ...        3     4        1     1        2        1     6   

            98    99    100  
animal     wolf  worm  wren  
hair          1     0     0  
feathers      0     0     1  
eggs          0     1     1  
milk          1     0     0  
airbourne     0     0     1  
aquatic       0     0     0  
predator      1     0     0  
toothed       1     0     0  
backbone      1     0     1  
breathes      1     1     1  
venomous      0     0     0  
fins          0     0     0  
legs          4     0     2  
tail          1     0     1  
domestic      0     0     0  
catsize       1     0     0  
type          1     7     2  

[18 rows x 101 columns]

### <br><br>Exercise 2

Write code to create a list of column names from `zoo_df`:

In [29]:
zoo_list = list(zoo_df.columns)
print(zoo_list)

['animal', 'hair', 'feathers', 'eggs', 'milk', 'airbourne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize', 'type']


Write code to return the data type for each column in `zoo_df`:

In [30]:
zoo_df.dtypes

animal       object
hair          int64
feathers      int64
eggs          int64
milk          int64
airbourne     int64
aquatic       int64
predator      int64
toothed       int64
backbone      int64
breathes      int64
venomous      int64
fins          int64
legs          int64
tail          int64
domestic      int64
catsize       int64
type          int64
dtype: object

## <br><br><br>PART TWO: SELECTING DATA

There are multiple ways to select data in pandas. You will need to learn all of the ways because you will see these techniques being used in other people's code and in answers to your pandas questions when you search online.
<br><br>We will cover:
- Selecting columns using DataFrame indexing
- Selecting rows based on a boolean condition using DataFrame indexing
- Selecting columns, rows, and individual data points with `loc` and `iloc`
- Selecting individual data points with `at` and `iat`
*You cannot select individual data points using indexing.*

We will work with the WNBA game data. Let's look at it again:

In [31]:
df.head()

season        date team1 team2               name1               name2  \
0    2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun   
1    2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics   
2    2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun   
3    2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics   
4    2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun   

   neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
0        0        1      89      78      1684      1634       1692       1627   
1        0        1      78      89      1634      1684       1627       1692   
2        0        1      86      90      1693      1626       1684       1634   
3        0        1      90      86      1626      1693       1634       1684   
4        0        1      94      81      1671      1648       1693       1626   

   prob1  is_home1  
0  0.718         1  
1  0.282         0  
2  0.476         0  
3  0.524         1  
4  0.399         0

### <br><br>Selecting columns or rows using indexing

To create a DataFrame with only some columns, you use indexing, and you pass it a list of the columns that you want to include:

In [32]:
my_columns = ["season", "team1", "team2"]
df[my_columns]

season team1 team2
0        2019   WAS   CON
1        2019   CON   WAS
2        2019   WAS   CON
3        2019   CON   WAS
4        2019   WAS   CON
...       ...   ...   ...
10483    1997   SAC   LVA
10484    1997   NYL   LAS
10485    1997   LAS   NYL
10486    1997   LVA   SAC
10487    1997   CLE   HOU

[10488 rows x 3 columns]

<br>OR you could just include the list inside the indexing. This creates two sets of square brackets, which looks a little silly, but it works!

In [33]:
df[["season", "team1", "team2"]]

season team1 team2
0        2019   WAS   CON
1        2019   CON   WAS
2        2019   WAS   CON
3        2019   CON   WAS
4        2019   WAS   CON
...       ...   ...   ...
10483    1997   SAC   LVA
10484    1997   NYL   LAS
10485    1997   LAS   NYL
10486    1997   LVA   SAC
10487    1997   CLE   HOU

[10488 rows x 3 columns]

<br>If you want to return just one column as a DataFrame, you still use the list inside the index:

In [34]:
df[["date"]]

date
0      10/10/2019
1      10/10/2019
2       10/8/2019
3       10/8/2019
4       10/6/2019
...           ...
10483   6/21/1997
10484   6/21/1997
10485   6/21/1997
10486   6/21/1997
10487   6/21/1997

[10488 rows x 1 columns]

### <br><br>Exercise 1

Here's a reminder of what the DataFrame looks like:

In [35]:
df.head()

season        date team1 team2               name1               name2  \
0    2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun   
1    2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics   
2    2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun   
3    2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics   
4    2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun   

   neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
0        0        1      89      78      1684      1634       1692       1627   
1        0        1      78      89      1634      1684       1627       1692   
2        0        1      86      90      1693      1626       1684       1634   
3        0        1      90      86      1626      1693       1634       1684   
4        0        1      94      81      1671      1648       1693       1626   

   prob1  is_home1  
0  0.718         1  
1  0.282         0  
2  0.476         0  
3  0.524         1  
4  0.399         0

Write code to return the name1, name2, and is_home1 columns:

In [36]:
df[["name1", "name2", "is_home1"]]

name1                name2  is_home1
0       Washington Mystics      Connecticut Sun         1
1          Connecticut Sun   Washington Mystics         0
2       Washington Mystics      Connecticut Sun         0
3          Connecticut Sun   Washington Mystics         1
4       Washington Mystics      Connecticut Sun         0
...                    ...                  ...       ...
10483  Sacramento Monarchs          Utah Starzz         0
10484     New York Liberty   Los Angeles Sparks         0
10485   Los Angeles Sparks     New York Liberty         1
10486          Utah Starzz  Sacramento Monarchs         1
10487    Cleveland Rockers       Houston Comets         1

[10488 rows x 3 columns]

Write code to return the playoff column:

In [37]:
df[["playoff"]]

playoff
0            1
1            1
2            1
3            1
4            1
...        ...
10483        0
10484        0
10485        0
10486        0
10487        0

[10488 rows x 1 columns]

<br><br><br>If you only index the column name, without putting it in a list, you get a different type of pandas object - the **Series** object.

In [38]:
df["date"]

0        10/10/2019
1        10/10/2019
2         10/8/2019
3         10/8/2019
4         10/6/2019
            ...    
10483     6/21/1997
10484     6/21/1997
10485     6/21/1997
10486     6/21/1997
10487     6/21/1997
Name: date, Length: 10488, dtype: object

<br>A Series object only returns the values from one column. It can be turned into a list, which is very convenient:

In [39]:
date_list = list(df["date"])
print(len(date_list))
print(type(date_list))
print(date_list[0:5])

10488
<class 'list'>
['10/10/2019', '10/10/2019', '10/8/2019', '10/8/2019', '10/6/2019']


<br>**A Series object is a one-dimensional object, while a DataFrame is a two-dimensional object. A Series can be turned into a list, while a DataFrame can be indexed based on row number, so they both have their uses.**

### <br><br>Exercise 2

Write code to return a list of data in the prob1 column:

In [40]:
prob_data = list(df["prob1"])

In [41]:
print(len(prob_data))
print(type(prob_data))

10488
<class 'list'>


### <br><br><br>Selecting rows using indexing

If we want to return a DataFrame with only some **rows**, we can index a range. DataFrame indexing uses regular Python indexing, so we ask for the first item we want, and then a colon, and then we go one position past the last item we want. 

In [42]:
df[0:10]

season        date team1 team2               name1               name2  \
0    2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun   
1    2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics   
2    2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun   
3    2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics   
4    2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun   
5    2019   10/6/2019   CON   WAS     Connecticut Sun  Washington Mystics   
6    2019   10/1/2019   WAS   CON  Washington Mystics     Connecticut Sun   
7    2019   10/1/2019   CON   WAS     Connecticut Sun  Washington Mystics   
8    2019   9/29/2019   WAS   CON  Washington Mystics     Connecticut Sun   
9    2019   9/29/2019   CON   WAS     Connecticut Sun  Washington Mystics   

   neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
0        0        1      89      78      1684      1634       1692       1627   
1        0        1      78      89      1634      1684       1627       1692   
2        0        1      86      90      1693      1626       1684       1634   
3        0        1      90      86      1626      1693       1634       1684   
4        0        1      94      81      1671      1648       1693       1626   
5        0        1      81      94      1648      1671       1626       1693   
6        0        1      87      99      1700      1618       1671       1648   
7        0        1      99      87      1618      1700       1648       1671   
8        0        1      95      86      1694      1624       1700       1618   
9        0        1      86      95      1624      1694       1618       1700   

   prob1  is_home1  
0  0.718         1  
1  0.282         0  
2  0.476         0  
3  0.524         1  
4  0.399         0  
5  0.601         1  
6  0.763         1  
7  0.237         0  
8  0.747         1  
9  0.253         0

<br>Because this indexing is referencing the position of the row in the DataFrame, not the index number, we an use negative indexing in either spot to count from the bottom of the DataFrame.

In [43]:
df[495:-12]

season       date team1 team2               name1                name2  \
495      2018  8/17/2018   DAL   LVA        Dallas Wings       Las Vegas Aces   
496      2018  8/17/2018   LVA   DAL      Las Vegas Aces         Dallas Wings   
497      2018  8/17/2018   NYL   SEA    New York Liberty        Seattle Storm   
498      2018  8/15/2018   WAS   IND  Washington Mystics        Indiana Fever   
499      2018  8/15/2018   LVA   NYL      Las Vegas Aces     New York Liberty   
...       ...        ...   ...   ...                 ...                  ...   
10471    1997  6/26/1997   CHA   SAC     Charlotte Sting  Sacramento Monarchs   
10472    1997  6/25/1997   LAS   CHA  Los Angeles Sparks      Charlotte Sting   
10473    1997  6/25/1997   CHA   LAS     Charlotte Sting   Los Angeles Sparks   
10474    1997  6/24/1997   HOU   PHO      Houston Comets      Phoenix Mercury   
10475    1997  6/24/1997   PHO   HOU     Phoenix Mercury       Houston Comets   

       neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
495          0        0     107     102      1461      1458       1468   
496          0        0     102     107      1458      1461       1451   
497          0        0      77      85      1328      1653       1326   
498          0        0      76      62      1591      1330       1599   
499          0        0      85      72      1451      1335       1458   
...        ...      ...     ...     ...       ...       ...        ...   
10471        0        0      70      78      1467      1501       1459   
10472        0        0      74      54      1468      1485       1486   
10473        0        0      54      74      1485      1468       1467   
10474        0        0      72      55      1530      1515       1544   
10475        0        0      55      72      1515      1530       1501   

       elo2_post  prob1  is_home1  
495         1451  0.618         1  
496         1468  0.382         0  
497         1655  0.088         0  
498         1322  0.740         0  
499         1328  0.755         1  
...          ...    ...       ...  
10471       1509  0.342         0  
10472       1467  0.590         1  
10473       1486  0.410         0  
10474       1501  0.634         1  
10475       1544  0.366         0  

[9981 rows x 16 columns]

<br>If you only want a single row, you still need to use indexing with a `:`:

In [44]:
df[4:5]

season       date team1 team2               name1            name2  \
4    2019  10/6/2019   WAS   CON  Washington Mystics  Connecticut Sun   

   neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
4        0        1      94      81      1671      1648       1693       1626   

   prob1  is_home1  
4  0.399         0

### <br><br>Exercise 3

Write code to return row number 9,999.

In [45]:
df[9999:10000]

season       date team1 team2                name1          name2  \
9999    1998  8/11/1998   SAC   DAL  Sacramento Monarchs  Detroit Shock   

      neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
9999        0        0      41      50      1369      1424       1354   

      elo2_post  prob1  is_home1  
9999       1439  0.537         1

Write code to return the second row in our DataFrame.

In [46]:
df[1:2]

season        date team1 team2            name1               name2  \
1    2019  10/10/2019   CON   WAS  Connecticut Sun  Washington Mystics   

   neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
1        0        1      78      89      1634      1684       1627       1692   

   prob1  is_home1  
1  0.282         0

### <br><br><br>Selecting data with a boolean

To return a DataFrame that only has rows that meet a certain condition, we use this syntax. The outer `df[]` lets Python know that you want the answer to be returned as a DataFrame, meaning you can return all the columns included in the output. Inside the indexing, we include our boolean statement, which usually means we need to index a particular column in the dataset to filter the data on.

In [47]:
df[df["team1"] == "LVA"]

season       date team1 team2           name1                name2  \
11       2019  9/24/2019   LVA   WAS  Las Vegas Aces   Washington Mystics   
14       2019  9/22/2019   LVA   WAS  Las Vegas Aces   Washington Mystics   
19       2019  9/19/2019   LVA   WAS  Las Vegas Aces   Washington Mystics   
23       2019  9/17/2019   LVA   WAS  Las Vegas Aces   Washington Mystics   
26       2019  9/15/2019   LVA   CHI  Las Vegas Aces          Chicago Sky   
...       ...        ...   ...   ...             ...                  ...   
10453    1997   7/2/1997   LVA   SAC     Utah Starzz  Sacramento Monarchs   
10463    1997  6/28/1997   LVA   HOU     Utah Starzz       Houston Comets   
10470    1997  6/26/1997   LVA   CLE     Utah Starzz    Cleveland Rockers   
10478    1997  6/23/1997   LVA   LAS     Utah Starzz   Los Angeles Sparks   
10486    1997  6/21/1997   LVA   SAC     Utah Starzz  Sacramento Monarchs   

       neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
11           0        1      90      94      1570      1687       1563   
14           0        1      92      75      1540      1717       1570   
19           0        1      91     103      1543      1714       1540   
23           0        1      95      97      1545      1712       1543   
26           0        1      93      92      1541      1564       1545   
...        ...      ...     ...     ...       ...       ...        ...   
10453        0        0      73      68      1456      1497       1470   
10463        0        0      58      76      1479      1535       1456   
10470        0        0      63      74      1491      1470       1479   
10478        0        0     102      89      1479      1481       1491   
10486        0        0      61      73      1500      1500       1479   

       elo2_post  prob1  is_home1  
11          1694  0.434         1  
14          1687  0.331         1  
19          1717  0.142         0  
23          1714  0.144         0  
26          1559  0.601         1  
...          ...    ...       ...  
10453       1483  0.332         0  
10463       1558  0.534         1  
10470       1482  0.416         0  
10478       1468  0.610         1  
10486       1521  0.613         1  

[802 rows x 16 columns]

In [48]:
df[df["score1"] > 100]

season       date team1 team2                name1  \
16       2019  9/19/2019   WAS   LVA   Washington Mystics   
28       2019  9/11/2019   CHI   PHO          Chicago Sky   
39       2019   9/8/2019   IND   CON        Indiana Fever   
45       2019   9/6/2019   CON   CHI      Connecticut Sun   
47       2019   9/6/2019   CHI   CON          Chicago Sky   
...       ...        ...   ...   ...                  ...   
9872     1999  6/24/1999   SAC   LVA  Sacramento Monarchs   
9961     1998  8/19/1998   CHA   WAS      Charlotte Sting   
9966     1998  8/17/1998   HOU   WAS       Houston Comets   
10464    1997  6/27/1997   LAS   SAC   Los Angeles Sparks   
10478    1997  6/23/1997   LVA   LAS          Utah Starzz   

                     name2  neutral  playoff  score1  score2  elo1_pre  \
16          Las Vegas Aces        0        1     103      91      1714   
28         Phoenix Mercury        0        1     105      76      1553   
39         Connecticut Sun        0        0     104      76      1424   
45             Chicago Sky        0        0     104     109      1615   
47         Connecticut Sun        0        0     109     104      1543   
...                    ...      ...      ...     ...     ...       ...   
9872           Utah Starzz        0        0     107      69      1465   
9961    Washington Mystics        0        0     105      69      1460   
9966    Washington Mystics        0        0     110      65      1695   
10464  Sacramento Monarchs        0        0     102      92      1486   
10478   Los Angeles Sparks        0        0     102      89      1479   

       elo2_pre  elo1_post  elo2_post  prob1  is_home1  
16         1543       1717       1540  0.858         1  
28         1450       1564       1440  0.788         1  
39         1599       1464       1559  0.367         1  
45         1543       1599       1559  0.705         1  
47         1615       1559       1599  0.295         0  
...         ...        ...        ...    ...       ...  
9872       1396       1484       1376  0.702         1  
9961       1183       1475       1168  0.757         0  
9966       1188       1700       1183  0.921         0  
10464      1509       1498       1497  0.582         1  
10478      1481       1491       1468  0.610         1  

[225 rows x 16 columns]

### <br><br>Exercise 4

Write code to return a DataFrame that only includes games that were playoff games (playoff games are coded as 1 in that column):

In [49]:
df[df["playoff"] == 1]

season        date team1 team2               name1               name2  \
0        2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun   
1        2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics   
2        2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun   
3        2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics   
4        2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun   
...       ...         ...   ...   ...                 ...                 ...   
10259    1997   8/30/1997   NYL   HOU    New York Liberty      Houston Comets   
10260    1997   8/28/1997   HOU   CHA      Houston Comets     Charlotte Sting   
10261    1997   8/28/1997   NYL   PHO    New York Liberty     Phoenix Mercury   
10262    1997   8/28/1997   PHO   NYL     Phoenix Mercury    New York Liberty   
10263    1997   8/28/1997   CHA   HOU     Charlotte Sting      Houston Comets   

       neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
0            0        1      89      78      1684      1634       1692   
1            0        1      78      89      1634      1684       1627   
2            0        1      86      90      1693      1626       1684   
3            0        1      90      86      1626      1693       1634   
4            0        1      94      81      1671      1648       1693   
...        ...      ...     ...     ...       ...       ...        ...   
10259        0        1      51      65      1532      1597       1524   
10260        0        1      70      54      1588      1512       1597   
10261        0        1      59      41      1496      1556       1532   
10262        0        1      41      59      1556      1496       1520   
10263        0        1      54      70      1512      1588       1503   

       elo2_post  prob1  is_home1  
0           1627  0.718         1  
1           1692  0.282         0  
2           1634  0.476         0  
3           1684  0.524         1  
4           1626  0.399         0  
...          ...    ...       ...  
10259       1605  0.261         0  
10260       1503  0.755         1  
10261       1520  0.267         0  
10262       1532  0.733         1  
10263       1597  0.245         0  

[768 rows x 16 columns]

In [50]:
df[df[["playoff"]] == 1]

season date team1 team2 name1 name2  neutral  playoff  score1  score2  \
0         NaN  NaN   NaN   NaN   NaN   NaN      NaN      1.0     NaN     NaN   
1         NaN  NaN   NaN   NaN   NaN   NaN      NaN      1.0     NaN     NaN   
2         NaN  NaN   NaN   NaN   NaN   NaN      NaN      1.0     NaN     NaN   
3         NaN  NaN   NaN   NaN   NaN   NaN      NaN      1.0     NaN     NaN   
4         NaN  NaN   NaN   NaN   NaN   NaN      NaN      1.0     NaN     NaN   
...       ...  ...   ...   ...   ...   ...      ...      ...     ...     ...   
10483     NaN  NaN   NaN   NaN   NaN   NaN      NaN      NaN     NaN     NaN   
10484     NaN  NaN   NaN   NaN   NaN   NaN      NaN      NaN     NaN     NaN   
10485     NaN  NaN   NaN   NaN   NaN   NaN      NaN      NaN     NaN     NaN   
10486     NaN  NaN   NaN   NaN   NaN   NaN      NaN      NaN     NaN     NaN   
10487     NaN  NaN   NaN   NaN   NaN   NaN      NaN      NaN     NaN     NaN   

       elo1_pre  elo2_pre  elo1_post  elo2_post  prob1  is_home1  
0           NaN       NaN        NaN        NaN    NaN       NaN  
1           NaN       NaN        NaN        NaN    NaN       NaN  
2           NaN       NaN        NaN        NaN    NaN       NaN  
3           NaN       NaN        NaN        NaN    NaN       NaN  
4           NaN       NaN        NaN        NaN    NaN       NaN  
...         ...       ...        ...        ...    ...       ...  
10483       NaN       NaN        NaN        NaN    NaN       NaN  
10484       NaN       NaN        NaN        NaN    NaN       NaN  
10485       NaN       NaN        NaN        NaN    NaN       NaN  
10486       NaN       NaN        NaN        NaN    NaN       NaN  
10487       NaN       NaN        NaN        NaN    NaN       NaN  

[10488 rows x 16 columns]

Write code to return a DataFrame that only includes games where score2 was greater than 100:

In [51]:
df[df["score2"] > 100]

season       date team1 team2                name1  \
19       2019  9/19/2019   LVA   WAS       Las Vegas Aces   
31       2019  9/11/2019   PHO   CHI      Phoenix Mercury   
35       2019   9/8/2019   CON   IND      Connecticut Sun   
45       2019   9/6/2019   CON   CHI      Connecticut Sun   
47       2019   9/6/2019   CHI   CON          Chicago Sky   
...       ...        ...   ...   ...                  ...   
9876     1999  6/24/1999   LVA   SAC          Utah Starzz   
9965     1998  8/19/1998   WAS   CHA   Washington Mystics   
9971     1998  8/17/1998   WAS   HOU   Washington Mystics   
10465    1997  6/27/1997   SAC   LAS  Sacramento Monarchs   
10479    1997  6/23/1997   LAS   LVA   Los Angeles Sparks   

                     name2  neutral  playoff  score1  score2  elo1_pre  \
19      Washington Mystics        0        1      91     103      1543   
31             Chicago Sky        0        1      76     105      1450   
35           Indiana Fever        0        0      76     104      1599   
45             Chicago Sky        0        0     104     109      1615   
47         Connecticut Sun        0        0     109     104      1543   
...                    ...      ...      ...     ...     ...       ...   
9876   Sacramento Monarchs        0        0      69     107      1396   
9965       Charlotte Sting        0        0      69     105      1183   
9971        Houston Comets        0        0      65     110      1188   
10465   Los Angeles Sparks        0        0      92     102      1509   
10479          Utah Starzz        0        0      89     102      1481   

       elo2_pre  elo1_post  elo2_post  prob1  is_home1  
19         1714       1540       1717  0.142         0  
31         1553       1440       1564  0.212         0  
35         1424       1559       1464  0.633         0  
45         1543       1599       1559  0.705         1  
47         1615       1559       1599  0.295         0  
...         ...        ...        ...    ...       ...  
9876       1465       1376       1484  0.298         0  
9965       1460       1168       1475  0.243         1  
9971       1695       1183       1700  0.079         1  
10465      1486       1497       1498  0.418         0  
10479      1479       1468       1491  0.390         0  

[225 rows x 16 columns]

<br><br><br>If you don't use the outer `df[]` the return is a Series object that returns the boolean value for each row based on the condition you set:

In [54]:
df["team1"] == "LVA"

0        False
1        False
2        False
3        False
4        False
         ...  
10483    False
10484    False
10485    False
10486     True
10487    False
Name: team1, Length: 10488, dtype: bool

### <br><br><br>Combining boolean indexing with column indexing

You can also combine a boolean with column indexing to return only some columns for your filtered data. Here I am returning only the team2, score1, and score2 columns for any rows with "CHI" in the team1 column.

In [55]:
df[df["team1"] == "CHI"][["team2", "score1", "score2"]]

team2  score1  score2
25     LVA      92      93
28     PHO     105      76
36     WAS      86     100
47     CON     109     104
65     PHO     105      78
...    ...     ...     ...
6371   HOU      60      71
6387   LAS      55      64
6393   IND      60      75
6415   SAC      63      76
6427   CHA      83      82

[497 rows x 3 columns]

### <br><br>Exercise 5

Write code to return all the games that were played in the 2017 season. Return only columns for date, team1, and team2.

In [56]:
df[df["season"] == 2017][["date", "team1", "team2"]]

date team1 team2
882   10/4/2017   MIN   LAS
883   10/4/2017   LAS   MIN
884   10/1/2017   MIN   LAS
885   10/1/2017   LAS   MIN
886   9/29/2017   LAS   MIN
...         ...   ...   ...
1315  5/13/2017   SEA   LAS
1316  5/13/2017   ATL   CON
1317  5/13/2017   NYL   LVA
1318  5/13/2017   CON   ATL
1319  5/13/2017   LVA   NYL

[438 rows x 3 columns]

<br><br><br>**Using the indexing method, we cannot refer to individual rows by name or pull up individual cells in our DataFrame.**

In [57]:
df[25]

KeyError: 25

### <br><br><br>pandas loc

The `loc` **attribute** allows us to call up certain rows and columns. The syntax is:

#### `df.loc[row, column]`

#### `df.loc[list of rows, list of columns]`

#### `df.loc[range of rows, range of columns]`

`loc` can take a row, a list of rows, or a range of rows, followed by a comma, and then a column, list of columns, or range of columns. <br><br>If you want all the rows or all the columns, you can use a `:`. <br><br>**The rows that we refer to here are the row names (index names) that are found in bold on the far left of our DataFrame.**

<br>To reference one cell:

In [58]:
df.loc[25, "date"]

'9/15/2019'

<br>All rows for one column:

In [59]:
df.loc[:, "team1"]

0        WAS
1        CON
2        WAS
3        CON
4        WAS
        ... 
10483    SAC
10484    NYL
10485    LAS
10486    LVA
10487    CLE
Name: team1, Length: 10488, dtype: object

<br>All columns for one row:

In [60]:
df.loc[12, :]

season                     2019
date                  9/22/2019
team1                       WAS
team2                       LVA
name1        Washington Mystics
name2            Las Vegas Aces
neutral                       0
playoff                       1
score1                       75
score2                       92
elo1_pre                   1717
elo2_pre                   1540
elo1_post                  1687
elo2_post                  1570
prob1                     0.669
is_home1                      0
Name: 12, dtype: object

### <br><br>Exercise 6

The very first game played by the Chicago Sky is in the row with index 6427.

Write code to return all columns in that row:

In [61]:
df.loc[6427, :]

season                  2006
date               5/20/2006
team1                    CHI
team2                    CHA
name1            Chicago Sky
name2        Charlotte Sting
neutral                    0
playoff                    0
score1                    83
score2                    82
elo1_pre                1300
elo2_pre                1428
elo1_post               1310
elo2_post               1418
prob1                  0.232
is_home1                   0
Name: 6427, dtype: object

Did the Chicago Sky play their very first game at home or away? Write code to return the data in the column "is_home1" for that row:

In [62]:
df.loc[6427, "is_home1"]

0

*(1 is True and 0 is False)* 

### <br><br>`loc` with a range and a list

This code will return all columns for the rows 0 through 10.

In [63]:
df.loc[0:10, :]

season        date team1 team2               name1               name2  \
0     2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun   
1     2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics   
2     2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun   
3     2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics   
4     2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun   
5     2019   10/6/2019   CON   WAS     Connecticut Sun  Washington Mystics   
6     2019   10/1/2019   WAS   CON  Washington Mystics     Connecticut Sun   
7     2019   10/1/2019   CON   WAS     Connecticut Sun  Washington Mystics   
8     2019   9/29/2019   WAS   CON  Washington Mystics     Connecticut Sun   
9     2019   9/29/2019   CON   WAS     Connecticut Sun  Washington Mystics   
10    2019   9/24/2019   WAS   LVA  Washington Mystics      Las Vegas Aces   

    neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
0         0        1      89      78      1684      1634       1692   
1         0        1      78      89      1634      1684       1627   
2         0        1      86      90      1693      1626       1684   
3         0        1      90      86      1626      1693       1634   
4         0        1      94      81      1671      1648       1693   
5         0        1      81      94      1648      1671       1626   
6         0        1      87      99      1700      1618       1671   
7         0        1      99      87      1618      1700       1648   
8         0        1      95      86      1694      1624       1700   
9         0        1      86      95      1624      1694       1618   
10        0        1      94      90      1687      1570       1694   

    elo2_post  prob1  is_home1  
0        1627  0.718         1  
1        1692  0.282         0  
2        1634  0.476         0  
3        1684  0.524         1  
4        1626  0.399         0  
5        1693  0.601         1  
6        1648  0.763         1  
7        1671  0.237         0  
8        1618  0.747         1  
9        1700  0.253         0  
10       1563  0.566         0

<br>**Unlike Python indexing, `loc` is referencing the rows by their index names, so row 10 is included.**

<br><br>We can also ask for a range of columns, from left to right:

In [64]:
df.loc[0:10, "season":"name2"]

season        date team1 team2               name1               name2
0     2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun
1     2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics
2     2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun
3     2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics
4     2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun
5     2019   10/6/2019   CON   WAS     Connecticut Sun  Washington Mystics
6     2019   10/1/2019   WAS   CON  Washington Mystics     Connecticut Sun
7     2019   10/1/2019   CON   WAS     Connecticut Sun  Washington Mystics
8     2019   9/29/2019   WAS   CON  Washington Mystics     Connecticut Sun
9     2019   9/29/2019   CON   WAS     Connecticut Sun  Washington Mystics
10    2019   9/24/2019   WAS   LVA  Washington Mystics      Las Vegas Aces

<br><br>Again, `loc` uses the column and row names, not their positions, so this will not work:

In [65]:
df.loc[0:10, 0:4]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

<br><br>We can also pass a list of rows or columns:

In [66]:
df.loc[[0, 10, 8], ["team1", "score1", "team2", "score2"]]

team1  score1 team2  score2
0    WAS      89   CON      78
10   WAS      94   LVA      90
8    WAS      95   CON      86

*Notice how the returned DataFrame used the same order given in the lists.*

### <br><br>Exercise 7

Run the following cell to store the list of row indexes for the first 5 games played by the Chicago Sky:

In [67]:
first5 = [6427, 6415, 6393, 6387, 6371]

Write code to return the rows for the first 5 Chicago Sky games, and return only the columns "team2", "score1", "score2", and "is_home1":

In [68]:
df.loc[first5, ["team2", "score1", "score2", "is_home1"]]

team2  score1  score2  is_home1
6427   CHA      83      82         0
6415   SAC      63      76         1
6393   IND      60      75         1
6387   LAS      55      64         1
6371   HOU      60      71         0

### <br><br>`loc` with a conditional

You can use a conditional to filter rows. The conditional is written the same way as we would write it without using loc:

In [69]:
df.loc[df["team1"] == "CHI", :]

season       date team1 team2        name1                name2  \
25      2019  9/15/2019   CHI   LVA  Chicago Sky       Las Vegas Aces   
28      2019  9/11/2019   CHI   PHO  Chicago Sky      Phoenix Mercury   
36      2019   9/8/2019   CHI   WAS  Chicago Sky   Washington Mystics   
47      2019   9/6/2019   CHI   CON  Chicago Sky      Connecticut Sun   
65      2019   9/1/2019   CHI   PHO  Chicago Sky      Phoenix Mercury   
...      ...        ...   ...   ...          ...                  ...   
6371    2006   6/2/2006   CHI   HOU  Chicago Sky       Houston Comets   
6387    2006  5/30/2006   CHI   LAS  Chicago Sky   Los Angeles Sparks   
6393    2006  5/26/2006   CHI   IND  Chicago Sky        Indiana Fever   
6415    2006  5/23/2006   CHI   SAC  Chicago Sky  Sacramento Monarchs   
6427    2006  5/20/2006   CHI   CHA  Chicago Sky      Charlotte Sting   

      neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
25          0        1      92      93      1564      1541       1559   
28          0        1     105      76      1553      1450       1564   
36          0        0      86     100      1559      1706       1553   
47          0        0     109     104      1543      1615       1559   
65          0        0     105      78      1522      1527       1543   
...       ...      ...     ...     ...       ...       ...        ...   
6371        0        0      60      71      1286      1575       1284   
6387        0        0      55      64      1294      1500       1286   
6393        0        0      60      75      1304      1548       1294   
6415        0        0      63      76      1310      1603       1304   
6427        0        0      83      82      1300      1428       1310   

      elo2_post  prob1  is_home1  
25         1545  0.399         0  
28         1440  0.788         1  
36         1712  0.214         0  
47         1599  0.295         0  
65         1506  0.607         1  
...         ...    ...       ...  
6371       1577  0.107         0  
6387       1508  0.326         1  
6393       1557  0.280         1  
6415       1610  0.227         1  
6427       1418  0.232         0  

[497 rows x 16 columns]

<br><br>Here I use the same filter for the rows, but I only ask for three columns to be returned:

In [70]:
df.loc[df["team1"] == "CHI", ["team2", "score1", "score2"]]

team2  score1  score2
25     LVA      92      93
28     PHO     105      76
36     WAS      86     100
47     CON     109     104
65     PHO     105      78
...    ...     ...     ...
6371   HOU      60      71
6387   LAS      55      64
6393   IND      60      75
6415   SAC      63      76
6427   CHA      83      82

[497 rows x 3 columns]

### <br><br>Exercise 8

Write code to return all games played in the 2012 season. Only return the columns "date", "name1", and "name2".

In [71]:
df.loc[df["season"] == 2012, ["date", "name1", "name2"]]

date               name1                     name2
3096  10/21/2012       Indiana Fever            Minnesota Lynx
3097  10/21/2012      Minnesota Lynx             Indiana Fever
3098  10/19/2012       Indiana Fever            Minnesota Lynx
3099  10/19/2012      Minnesota Lynx             Indiana Fever
3100  10/17/2012      Minnesota Lynx             Indiana Fever
...          ...                 ...                       ...
3537   5/19/2012         Chicago Sky        Washington Mystics
3538   5/19/2012  Washington Mystics               Chicago Sky
3539   5/19/2012         Tulsa Shock  San Antonio Silver Stars
3540   5/18/2012       Seattle Storm        Los Angeles Sparks
3541   5/18/2012  Los Angeles Sparks             Seattle Storm

[446 rows x 3 columns]

### <br><br><br>pandas `iloc`

**While `loc` searches by row and column names, `iloc` searches only by the indexed positions in the DataFrame.**

Here, I'm asking for the top 10 rows and the first four columns:

In [72]:
df.iloc[0:10, 0:4]

season        date team1 team2
0    2019  10/10/2019   WAS   CON
1    2019  10/10/2019   CON   WAS
2    2019   10/8/2019   WAS   CON
3    2019   10/8/2019   CON   WAS
4    2019   10/6/2019   WAS   CON
5    2019   10/6/2019   CON   WAS
6    2019   10/1/2019   WAS   CON
7    2019   10/1/2019   CON   WAS
8    2019   9/29/2019   WAS   CON
9    2019   9/29/2019   CON   WAS

<br>**Notice that `iloc` uses Python indexing!** When we ask for rows 0:10, it returns rows 0 to 9. Also notice that the index (the bold number on the left side of each row) does not count as a true column.

<br>Because `iloc` uses Python indexing, we can use negative numbers:

In [73]:
df.iloc[0:-5000, 4:-10]

name1                     name2
0           Washington Mystics           Connecticut Sun
1              Connecticut Sun        Washington Mystics
2           Washington Mystics           Connecticut Sun
3              Connecticut Sun        Washington Mystics
4           Washington Mystics           Connecticut Sun
...                        ...                       ...
5483        Los Angeles Sparks            Houston Comets
5484           Phoenix Mercury       Sacramento Monarchs
5485           Connecticut Sun          New York Liberty
5486             Indiana Fever  San Antonio Silver Stars
5487  San Antonio Silver Stars             Indiana Fever

[5488 rows x 2 columns]

### <br><br>Exercise 9

The games are included in reverse chronological order, so the last row in the table is the very first game ever played.

Was the very first game played at home or away for team1? Use iloc to return the column "is_home1" for the very last row in the DataFrame:

In [74]:
df.iloc[-1, -1]

1

Use iloc to write code to return the columns "team1" and "team2" for the most recent 20 games:

In [75]:
df.iloc[:20, 2:4]

team1 team2
0    WAS   CON
1    CON   WAS
2    WAS   CON
3    CON   WAS
4    WAS   CON
5    CON   WAS
6    WAS   CON
7    CON   WAS
8    WAS   CON
9    CON   WAS
10   WAS   LVA
11   LVA   WAS
12   WAS   LVA
13   CON   LAS
14   LVA   WAS
15   LAS   CON
16   WAS   LVA
17   CON   LAS
18   LAS   CON
19   LVA   WAS

### <br><br><br>pandas `at` and `iat`

If you are looking for the contents of only a single cell (called a **scalar**) in the DataFrame, you can use `loc` or `iloc`:

In [76]:
df.loc[0, "season"]

2019

In [77]:
df.iloc[0, 0]

2019

<br>However, there is another set of pandas functions designed to look up only a single cell. `at` will look up a single cell by row name and column name (like `loc`), and `iat` will look up a single cell by index position (like `iloc`).

Why does pandas have a separate way to look up a single cell? Because `at` and `iat` are very fast. If you write code to look up 10,000 single points in a DataFrame, it would be much faster to use `at` or `iat` than `loc` or `iloc`.

In [78]:
df.at[0, "season"]

2019

In [79]:
df.iat[0, 0]

2019

<br><br>Just to reiterate, `at` and `iat` cannot be used with multiple rows or columns:

In [80]:
df.at[0, ["season", "date"]]

TypeError: unhashable type: 'list'

### <br><br>Exercise 10

Use `at` to write code to find out if the game in row 5485 was played at home or away:

In [81]:
df.at[5485, "is_home1"]

0

Now use `iat` to find the same answer:

In [82]:
df.iat[5485, -1]

0

### <br><br>A note about index labels

The bold numbers on the far left of each column were assigned to each row when the csv file was originally loaded into pandas.

In [83]:
df.head()

season        date team1 team2               name1               name2  \
0    2019  10/10/2019   WAS   CON  Washington Mystics     Connecticut Sun   
1    2019  10/10/2019   CON   WAS     Connecticut Sun  Washington Mystics   
2    2019   10/8/2019   WAS   CON  Washington Mystics     Connecticut Sun   
3    2019   10/8/2019   CON   WAS     Connecticut Sun  Washington Mystics   
4    2019   10/6/2019   WAS   CON  Washington Mystics     Connecticut Sun   

   neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
0        0        1      89      78      1684      1634       1692       1627   
1        0        1      78      89      1634      1684       1627       1692   
2        0        1      86      90      1693      1626       1684       1634   
3        0        1      90      86      1626      1693       1634       1684   
4        0        1      94      81      1671      1648       1693       1626   

   prob1  is_home1  
0  0.718         1  
1  0.282         0  
2  0.476         0  
3  0.524         1  
4  0.399         0

<br>If we make a new DataFrame out of only some rows, the index labels will stay the same, leaving gaps. Let's make a new DataFrame that only includes games played by the Chicago Sky:

In [84]:
CHIdf = df.loc[df["team1"] == "CHI", :]
CHIdf.head()

season       date team1 team2        name1               name2  neutral  \
25    2019  9/15/2019   CHI   LVA  Chicago Sky      Las Vegas Aces        0   
28    2019  9/11/2019   CHI   PHO  Chicago Sky     Phoenix Mercury        0   
36    2019   9/8/2019   CHI   WAS  Chicago Sky  Washington Mystics        0   
47    2019   9/6/2019   CHI   CON  Chicago Sky     Connecticut Sun        0   
65    2019   9/1/2019   CHI   PHO  Chicago Sky     Phoenix Mercury        0   

    playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  prob1  \
25        1      92      93      1564      1541       1559       1545  0.399   
28        1     105      76      1553      1450       1564       1440  0.788   
36        0      86     100      1559      1706       1553       1712  0.214   
47        0     109     104      1543      1615       1559       1599  0.295   
65        0     105      78      1522      1527       1543       1506  0.607   

    is_home1  
25         0  
28         1  
36         0  
47         0  
65         1

<br>I can now use `iloc` to get Chicago's most recent 30 games:

In [85]:
CHIdf.iloc[0:30, :]

season       date team1 team2        name1               name2  neutral  \
25     2019  9/15/2019   CHI   LVA  Chicago Sky      Las Vegas Aces        0   
28     2019  9/11/2019   CHI   PHO  Chicago Sky     Phoenix Mercury        0   
36     2019   9/8/2019   CHI   WAS  Chicago Sky  Washington Mystics        0   
47     2019   9/6/2019   CHI   CON  Chicago Sky     Connecticut Sun        0   
65     2019   9/1/2019   CHI   PHO  Chicago Sky     Phoenix Mercury        0   
78     2019  8/29/2019   CHI   DAL  Chicago Sky        Dallas Wings        0   
86     2019  8/27/2019   CHI   MIN  Chicago Sky      Minnesota Lynx        0   
96     2019  8/25/2019   CHI   PHO  Chicago Sky     Phoenix Mercury        0   
107    2019  8/23/2019   CHI   WAS  Chicago Sky  Washington Mystics        0   
117    2019  8/20/2019   CHI   ATL  Chicago Sky       Atlanta Dream        0   
128    2019  8/18/2019   CHI   LVA  Chicago Sky      Las Vegas Aces        0   
135    2019  8/16/2019   CHI   LAS  Chicago Sky  Los Angeles Sparks        0   
157    2019  8/11/2019   CHI   LAS  Chicago Sky  Los Angeles Sparks        0   
167    2019   8/9/2019   CHI   LVA  Chicago Sky      Las Vegas Aces        0   
174    2019   8/7/2019   CHI   NYL  Chicago Sky    New York Liberty        0   
187    2019   8/3/2019   CHI   ATL  Chicago Sky       Atlanta Dream        0   
206    2019  7/30/2019   CHI   CON  Chicago Sky     Connecticut Sun        0   
221    2019  7/21/2019   CHI   IND  Chicago Sky       Indiana Fever        0   
239    2019  7/17/2019   CHI   ATL  Chicago Sky       Atlanta Dream        0   
247    2019  7/14/2019   CHI   DAL  Chicago Sky        Dallas Wings        0   
259    2019  7/12/2019   CHI   NYL  Chicago Sky    New York Liberty        0   
269    2019  7/10/2019   CHI   MIN  Chicago Sky      Minnesota Lynx        0   
278    2019   7/7/2019   CHI   DAL  Chicago Sky        Dallas Wings        0   
294    2019   7/2/2019   CHI   LVA  Chicago Sky      Las Vegas Aces        0   
300    2019  6/30/2019   CHI   LAS  Chicago Sky  Los Angeles Sparks        0   
310    2019  6/28/2019   CHI   SEA  Chicago Sky       Seattle Storm        0   
318    2019  6/26/2019   CHI   WAS  Chicago Sky  Washington Mystics        0   
327    2019  6/23/2019   CHI   CON  Chicago Sky     Connecticut Sun        0   
339    2019  6/21/2019   CHI   IND  Chicago Sky       Indiana Fever        0   
346    2019  6/19/2019   CHI   NYL  Chicago Sky    New York Liberty        0   

     playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  prob1  \
25         1      92      93      1564      1541       1559       1545  0.399   
28         1     105      76      1553      1450       1564       1440  0.788   
36         0      86     100      1559      1706       1553       1712  0.214   
47         0     109     104      1543      1615       1559       1599  0.295   
65         0     105      78      1522      1527       1543       1506  0.607   
78         0      83      88      1541      1395       1522       1413  0.787   
86         0      85      93      1551      1539       1541       1548  0.404   
96         0      94      86      1535      1522       1551       1506  0.405   
107        0      85      78      1519      1692       1535       1676  0.369   
117        0      87      83      1513      1347       1519       1341  0.621   
128        0      85     100      1536      1552       1513       1576  0.591   
135        0      91      81      1524      1560       1536       1548  0.563   
157        0      81      84      1529      1570       1524       1575  0.332   
167        0      87      84      1518      1551       1529       1539  0.343   
174        0     101      92      1512      1375       1518       1370  0.777   
187        0      87      75      1498      1393       1512       1378  0.536   
206        0      94     100      1503      1585       1498       1590  0.282   
221        0      78      70      1497      1400       1503       

<br>But I could not use `loc` to get the same thing:

In [86]:
CHIdf.loc[0:30, :]

season       date team1 team2        name1            name2  neutral  \
25    2019  9/15/2019   CHI   LVA  Chicago Sky   Las Vegas Aces        0   
28    2019  9/11/2019   CHI   PHO  Chicago Sky  Phoenix Mercury        0   

    playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  prob1  \
25        1      92      93      1564      1541       1559       1545  0.399   
28        1     105      76      1553      1450       1564       1440  0.788   

    is_home1  
25         0  
28         1

<br>You can, however, set one of your columns as the index labels:

In [87]:
CHIdf = CHIdf.set_index("date")

In [88]:
CHIdf.head()

season team1 team2        name1               name2  neutral  \
date                                                                      
9/15/2019    2019   CHI   LVA  Chicago Sky      Las Vegas Aces        0   
9/11/2019    2019   CHI   PHO  Chicago Sky     Phoenix Mercury        0   
9/8/2019     2019   CHI   WAS  Chicago Sky  Washington Mystics        0   
9/6/2019     2019   CHI   CON  Chicago Sky     Connecticut Sun        0   
9/1/2019     2019   CHI   PHO  Chicago Sky     Phoenix Mercury        0   

           playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
date                                                                           
9/15/2019        1      92      93      1564      1541       1559       1545   
9/11/2019        1     105      76      1553      1450       1564       1440   
9/8/2019         0      86     100      1559      1706       1553       1712   
9/6/2019         0     109     104      1543      1615       1559       1599   
9/1/2019         0     105      78      1522      1527       1543       1506   

           prob1  is_home1  
date                        
9/15/2019  0.399         0  
9/11/2019  0.788         1  
9/8/2019   0.214         0  
9/6/2019   0.295         0  
9/1/2019   0.607         1

<br>Now I can use `loc` to reference the games by date:

In [89]:
CHIdf.loc["9/13/2012", :]

season                     2012
team1                       CHI
team2                       LAS
name1               Chicago Sky
name2        Los Angeles Sparks
neutral                       0
playoff                       0
score1                       77
score2                       86
elo1_pre                   1490
elo2_pre                   1566
elo1_post                  1483
elo2_post                  1573
prob1                      0.29
is_home1                      0
Name: 9/13/2012, dtype: object

<br><br>I can still use a range of row labels:

In [90]:
CHIdf.loc["9/13/2012":"5/19/2012", :]

season team1 team2        name1                     name2  neutral  \
date                                                                            
9/13/2012    2012   CHI   LAS  Chicago Sky        Los Angeles Sparks        0   
9/11/2012    2012   CHI   MIN  Chicago Sky            Minnesota Lynx        0   
9/9/2012     2012   CHI   CON  Chicago Sky           Connecticut Sun        0   
9/7/2012     2012   CHI   NYL  Chicago Sky          New York Liberty        0   
9/2/2012     2012   CHI   LAS  Chicago Sky        Los Angeles Sparks        0   
9/1/2012     2012   CHI   IND  Chicago Sky             Indiana Fever        0   
8/28/2012    2012   CHI   CON  Chicago Sky           Connecticut Sun        0   
8/26/2012    2012   CHI   CON  Chicago Sky           Connecticut Sun        0   
8/24/2012    2012   CHI   DAL  Chicago Sky               Tulsa Shock        0   
8/22/2012    2012   CHI   ATL  Chicago Sky             Atlanta Dream        0   
8/21/2012    2012   CHI   NYL  Chicago Sky          New York Liberty        0   
8/19/2012    2012   CHI   WAS  Chicago Sky        Washington Mystics        0   
8/17/2012    2012   CHI   ATL  Chicago Sky             Atlanta Dream        0   
7/13/2012    2012   CHI   CON  Chicago Sky           Connecticut Sun        0   
7/11/2012    2012   CHI   LVA  Chicago Sky  San Antonio Silver Stars        0   
7/7/2012     2012   CHI   IND  Chicago Sky             Indiana Fever        0   
7/6/2012     2012   CHI   NYL  Chicago Sky          New York Liberty        0   
7/1/2012     2012   CHI   ATL  Chicago Sky             Atlanta Dream        0   
6/29/2012    2012   CHI   PHO  Chicago Sky           Phoenix Mercury        0   
6/27/2012    2012   CHI   IND  Chicago Sky             Indiana Fever        0   
6/23/2012    2012   CHI   MIN  Chicago Sky            Minnesota Lynx        0   
6/16/2012    2012   CHI   IND  Chicago Sky             Indiana Fever        0   
6/13/2012    2012   CHI   SEA  Chicago Sky             Seattle Storm        0   
6/10/2012    2012   CHI   NYL  Chicago Sky          New York Liberty        0   
6/8/2012     2012   CHI   DAL  Chicago Sky               Tulsa Shock        0   
6/2/2012     2012   CHI   ATL  Chicago Sky             Atlanta Dream        0   
6/1/2012     2012   CHI   WAS  Chicago Sky        Washington Mystics        0   
5/30/2012    2012   CHI   LVA  Chicago Sky  San Antonio Silver Stars        0   
5/25/2012    2012   CHI   IND  Chicago Sky             Indiana Fever        0   
5/19/2012    2012   CHI   WAS  Chicago Sky        Washington Mystics        0   

           playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  elo2_post  \
date                                                                           
9/13/2012        0      77      86      1490      1566       1483       1573   
9/11/2012        0      83      70      1460      1727       1490       1697   
9/9/2012         0      77      82      1465      1552       1460       1556   
9/7/2012         0      92      83      1446      1460       1465       1442   
9/2/2012         0      85      74      1426      1585       1446       1565   
9/1/2012         0      64      81      1433      1592       1426       1599   
8/28/2012        0      72      83      1447      1550       1433       1564   
8/26/2012        0      82      70      1415      1583       1447       1550   
8/24/2012        0      78      81      1423      1325       1415       1333   
8/22/2012        0      71      82      1430      1539       1423       1545   
8/21/2012        0      67      77      1449      1452       1430       1471   
8/19/2012        0      71      75      1458      1358       1449       1368   
8/17/2012        0      76      82      1469      1540       1458       1552   
7/13/2012        0      78      80      1475      1592       1469       1598   
7/11/2012        0      68      77      1486      1620       1475       1631   
7/7/2012         0      86      88      1490      1553    

<br>If you've been wondering why referencing rows by index numbers would ever be useful, now you can set your index names to any unique value that would be useful to you - a sample ID, a name, a date, etc.

### <br><br>Exercise 11

Using the CHIdf, write code (use either `loc` or `at`) to find out which team Chicago played against on 6/16/2017:

In [93]:
CHIdf.loc["6/16/2017", "team2"]

'PHO'

In [94]:
CHIdf.at["6/16/2017", "team2"]

'PHO'

### <br><br><br>Searching for multiple conditionals in pandas

Let's say we want to search through the original DataFrame, `df`, for all games played by the Chicago Sky where the Chicago Sky won. For each of these games, we want to return only the columns for season and the name of the opposing team.

The conditional for only Chicago Sky games is:
<br>`df["team1"] == "CHI"`
<br><br>The conditional for games that Chicago won is:
<br>`df["score1"] > df["score2"]`

We might try to use Python operators (`and`, `or`, `not`):

In [95]:
df.loc[df["team1"] == "CHI" and df["score1"] > df["score2"], ["season", "name2"]]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

<br><br>**However, pandas uses the operators `&`, `|`, `!` for and, or, and not. Pandas also requires you to include each conditional inside parentheses.**

In [96]:
df.loc[(df["team1"] == "CHI") & (df["score1"] > df["score2"]), ["season", "team2"]]

season team2
28      2019   PHO
47      2019   CON
65      2019   PHO
96      2019   PHO
107     2019   WAS
...      ...   ...
5961    2006   IND
6069    2006   MIN
6183    2006   NYL
6223    2006   CHA
6427    2006   CHA

[220 rows x 2 columns]

### <br><br>Exercise 12

Use `loc` to return rows in the DataFrame that were played in either the 1999 or 2000 seasons. For each row, return all columns:

In [97]:
df.loc[(df["season"] == 1999) | (df["season"] == 2000), :]

season       date team1 team2                name1                name2  \
8992    2000  8/26/2000   HOU   NYL       Houston Comets     New York Liberty   
8993    2000  8/26/2000   NYL   HOU     New York Liberty       Houston Comets   
8994    2000  8/24/2000   HOU   NYL       Houston Comets     New York Liberty   
8995    2000  8/24/2000   NYL   HOU     New York Liberty       Houston Comets   
8996    2000  8/21/2000   NYL   CLE     New York Liberty    Cleveland Rockers   
...      ...        ...   ...   ...                  ...                  ...   
9937    1999  6/10/1999   LAS   SAC   Los Angeles Sparks  Sacramento Monarchs   
9938    1999  6/10/1999   CHA   WAS      Charlotte Sting   Washington Mystics   
9939    1999  6/10/1999   SAC   LAS  Sacramento Monarchs   Los Angeles Sparks   
9940    1999  6/10/1999   WAS   CHA   Washington Mystics      Charlotte Sting   
9941    1999  6/10/1999   CON   HOU      Orlando Miracle       Houston Comets   

      neutral  playoff  score1  score2  elo1_pre  elo2_pre  elo1_post  \
8992        0        1      79      73      1741      1523       1743   
8993        0        1      73      79      1523      1741       1522   
8994        0        1      59      52      1735      1529       1741   
8995        0        1      52      59      1529      1735       1523   
8996        0        1      81      67      1521      1460       1529   
...       ...      ...     ...     ...       ...       ...        ...   
9937        0        0     100      78      1482      1423       1496   
9938        0        0      83      73      1482      1334       1493   
9939        0        0      78     100      1423      1482       1410   
9940        0        0      73      83      1334      1482       1323   
9941        0        0      63      77      1300      1606       1293   

      elo2_post  prob1  is_home1  
8992       1522  0.895         1  
8993       1743  0.105         0  
8994       1523  0.712         0  
8995       1741  0.288         1  
8996       1451  0.734         1  
...         ...    ...       ...  
9937       1410  0.689         1  
9938       1323  0.597         0  
9939       1496  0.311         0  
9940       1493  0.403         1  
9941       1613  0.214         1  

[950 rows x 16 columns]

Has Chicago ever played in any playoff games? Return rows that have CHI in the "team1" column and 1 in the "playoff" column. Only return the columns "season", "team2", and "date":

In [99]:
df.loc[(df["team1"] == "CHI") & (df["playoff"] == 1), ["season", "team2", "date"]]

season team2       date
25      2019   LVA  9/15/2019
28      2019   PHO  9/11/2019
1331    2016   LAS  10/4/2016
1335    2016   LAS  10/2/2016
1339    2016   LAS  9/30/2016
1343    2016   LAS  9/28/2016
1344    2016   ATL  9/25/2016
1785    2015   IND  9/21/2015
1791    2015   IND  9/19/2015
1799    2015   IND  9/17/2015
2211    2014   PHO  9/12/2014
2213    2014   PHO   9/9/2014
2215    2014   PHO   9/7/2014
2216    2014   IND   9/3/2014
2221    2014   IND   9/1/2014
2225    2014   IND  8/30/2014
2229    2014   ATL  8/26/2014
2233    2014   ATL  8/24/2014
2241    2014   ATL  8/22/2014
2674    2013   IND  9/22/2013
2681    2013   IND  9/20/2013

## <br><br><br>PART THREE: *OPEN UP THE NOTEBOOK PANDAS2.IPYNB*

We don't want our notebook to get too slow as we continue to work with additional dataframes.